apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notificationservice
  namespace: kwetter-development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notificationservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80